Repository w3c/webrtc-encoded-transform, pull requests merged in 2023-10, with the labels that each got.

#204 Move RTP timestamp members to Metadata objects
  index.bs
Labels: Editors can integrate

#208 Remove (de)serialization of no longer existent RTCEncodedVideoFrame.timestamp
  index.bs
Labels: editorial

#140 add mimeType to metadata
  index.bs
Labels: enhancement, Submitter action needed
